# All the color setting are under the "color" section.
colors:
    # Default colors
    primary:
        background: '#222222'
        foregroud:  '#FFFFFF'
# Normal colors
    normal:
        black:   '0x000000'
        red:     '0xFF4652'
        green:   '0x40FF43'
        yellow:  '0xFBFF00'
        blue:    '0x4B97E2'
        magenta: '0xD974FF'
        cyan:    '0x59EBFF'
        white:   '0xFFFFFF'

        #  Bright colors
    bright:
        black:   '0x000000'
        red:     '0xFF4652'
        green:   '0x40FF43'
        yellow:  '0xFBFF00'
        blue:    '0x4B97E2'
        magenta: '0xD974FF'
        cyan:    '0x59EBFF'
        white:   '0xFFFFFF'
font:
    size: 12
    normal:
        family: DEC Terminal
