#!/usr/bin/env python

from optparse import OptionParser
import sys
import re
import os

def main():
    # Add command line options to parse
    parser = OptionParser()
    parser.add_option("-o", "--outfile", 
                        action="store", type="string", dest="outfile")
    parser.add_option("-t", "--type", 
                        action="store", type="string", dest="compile_type")

    (options, args) = parser.parse_args()
    if len(args) != 1:
        sys.exit("Error: Requires exactly one file to compile") 
    input_file = args[0]
    out_type = options.compile_type
    out_file = options.outfile
    if out_type != 'html':
        # Default to pdf
        out_type = 'pdf'
        
    if not out_file:
        # Find file name and suffix, assume it has extension .md
        m = re.search(r'(.*).md(.*)?', input_file)
        fileName = m.group(1)
        suffix = m.group(2)
        # Default out_file
        out_file = fileName + '.' + out_type + suffix

    command = []
    if out_type == 'pdf':
        command.append('markdown-pdf')
    else:
        command.append('marked')
    command.extend([input_file, '-o', out_file])
    commandString = ' '.join(command)
    os.system(commandString)
    
if __name__ == "__main__":
    main()
