# Includes all necessary places for path
export PATH="$HOME/bin/apache-maven-3.6.3/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
fpath+=~/.zsh

# Expose custom commands
source ~/.zsh/custom_commands.sh

# Expose custom aliases
source ~/.zsh/alias.sh

# Java Default set to 1.8
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

bindkey -v
export PATH="/usr/local/sbin:$PATH"

export PATH="/usr/local/sbin:/Users/cbpodd/bin/apache-maven-3.6.3/bin:/Users/cbpodd/.yarn/bin:/Users/cbpodd/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin"
