# Variables
export PATH=":/Users/cbpodd/sbin:/usr/local/bin:/usr/local/sbin:/Users/cbpodd/.yarn/bin:/Users/cbpodd/.config/yarn/global/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Path variables
export repos="$HOME/repos"
export ONEDRIVE="$HOME/OneDrive"
export School="$ONEDRIVE/School"
export shared="$ONEDRIVE/shared"
export money="$shared/money"
export mymoney="$money/cam"

# Include secrets (not included in source control)
source $HOME/.secret.sh

# Zsh Config
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#B3B3B3'
source ~/.config/antigen.zsh
antigen init ~/.config/antigen/antigenrc
export EDITOR=vim
fpath+=~/.config

# Custom Commands
RIGHT_MON_ID='E0CF5B67-FDDF-13D4-8C8D-64D7900F18A8'
LEFT_MON_ID='6652BC2D-F818-E3CE-F64D-C9E890B19458'
INTERNAL_SCREEN_ID='1B6E5E4F-F885-D5D9-12AC-423EA9E16E72'

INTERNAL_MODE='res:1680x1050 color_depth:8 scaling:on'
MON_MODE='res:1680x1050 hz:59 color_depth:4 scaling:off'
SINGLE_MODE='res:1280x800 color_depth:8 scaling:on'
NO_ROTATE='degree:0'

function normalDisplays() {
    displayplacer\
        "id:$INTERNAL_SCREEN_ID $INTERNAL_MODE origin:(1680,0) degree:0" \
        "id:$RIGHT_MON_ID $MON_MODE $NO_ROTATE origin:(0,0)" \
        "id:$LEFT_MON_ID $MON_MODE $NO_ROTATE origin:(-1680,0)"
}

function mirrorDisplays() {
    displayplacer "id:$RIGHT_MON_ID+$LEFT_MON_ID+$INTERNAL_SCREEN_ID $MON_MODE $NO_ROTATE origin:(0,0)"
}

function singleDisplay() {
    displayplacer "id:$INTERNAL_SCREEN_ID $SINGLE_MODE $NO_ROTATE origin:(0,0)"
}

function cdb() {
    initialString='../'
    finalString=$initialString
    iterations=1
    if test $# -eq 1; then
        iterations=$1
    fi

    for _ in {1..$iterations}; do
        finalString="$initialString$finalString"
    done

    cd $finalString
}

# Git Scripts
function gacp() {
    git add .
    git commit -m $1
    git push
}

# Aliases

# Overwrites of existing commands for better defaults
alias mv="mv -i"             # -i prompts before overwrite
alias mkdir="mkdir -p"       # -p makes parents dirs as needed
alias cp="cp -r"             # -r copies directories recursively
alias make="make -j$(nproc)" # -j$(nproc) uses nproc concurrent jobs
alias cat="cat -n"           # -n displays line numbers

# Common Flags
alias la="ls -A"
alias ll="ls -lh"
alias lla="ll -A"
alias rmd="rm -rf"

# Git
alias ga="git add ."
alias gtcm="git commit -S -m"
alias gs="git status"
alias gpl="git pull"
alias gph="git push"
alias gb="git branch"
alias gch="git checkout"
alias ggraph="git log --oneline --graph --decorate --all"
alias gdcm='git add . && git commit -S -m "Default Commit Message" && git push'

# VirtualBox Command Line
alias vbox="VBoxManage"
alias vbst='vbox startvm "Ubuntu Server" --type headless'
alias vbsp='vbox controlvm "Ubuntu Server" poweroff --type headless'
alias vboxc='vbsa && ssh vbox && vbso'

# Shpotify - Spotify Command Line
alias sn="spotify next"
alias spv="spotify prev"
alias sp="spotify pause"
alias ss="spotify status"

# Common Vim Commands
alias :e=vim

# Python
alias pserver="python3 -m http.server 4444"
alias py="python"
alias p3="python3"

# My own displayplacer commands
alias nd="normalDisplays"
alias md="mirrorDisplays"
alias sd="singleDisplay"

# Others
alias rq='sed -E "s/\"//g"'
alias preview='open -a "Preview.app"'

# Noglobs
alias mergepdfs='noglob mergepdfs'
